import React from 'react';
import { ScrollView, View, Text, StyleSheet, Linking, Alert } from 'react-native';

const Privacy = () => {
  const handleLinkPress = (url) => {
    Linking.openURL(url).catch(() => {
      Alert.alert('Error', 'Unable to open link');
    });
  };

  const handleEmailPress = (email) => {
    Linking.openURL(`mailto:${email}`).catch(() => {
      Alert.alert('Error', 'Unable to open email client');
    });
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <View style={styles.content}>
        <Text style={styles.title}>PRIVACY POLICY</Text>

        <Text style={styles.effectiveDate}>Effective date: 2025-06-13</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. Introduction</Text>
          <Text style={styles.paragraph}>
            Welcome to <Text style={styles.bold}>Labor Link Pvt Ltd</Text>.
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Labor Link Pvt Ltd </Text> ("us", "we", or "our") operates{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500')}>
              http://localhost:8500
            </Text>{' '}
            (hereinafter referred to as <Text style={styles.bold}>"Service"</Text>).
          </Text>
          <Text style={styles.paragraph}>
            Our Privacy Policy governs your visit to{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500')}>
              http://localhost:8500
            </Text>, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          </Text>
          <Text style={styles.paragraph}>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </Text>
          <Text style={styles.paragraph}>
            Our Terms and Conditions (<Text style={styles.bold}>"Terms"</Text>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<Text style={styles.bold}>"agreement"</Text>).
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. Definitions</Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>SERVICE</Text> means the{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500')}>
              http://localhost:8500
            </Text>{' '}
            website operated by Labor Link Pvt Ltd.
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>PERSONAL DATA</Text> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>USAGE DATA</Text> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>COOKIES</Text> are small files stored on your device (computer or mobile device).
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA CONTROLLER</Text> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA PROCESSORS (OR SERVICE PROVIDERS)</Text> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA SUBJECT</Text> is any living individual who is the subject of Personal Data.
          </Text>
          <Text style={styles.paragraph}>
            <Text style={styles.bold}>THE USER</Text> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Information Collection and Use</Text>
          <Text style={styles.paragraph}>
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>4. Types of Data Collected</Text>

          <Text style={styles.subsectionTitle}>Personal Data</Text>
          <Text style={styles.paragraph}>
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (<Text style={styles.bold}>"Personal Data"</Text>). Personally identifiable information may include, but is not limited to:
          </Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• Email address</Text>
            <Text style={styles.listItem}>• First name and last name</Text>
            <Text style={styles.listItem}>• Phone number</Text>
            <Text style={styles.listItem}>• Address, Country, State, Province, ZIP/Postal code, City</Text>
            <Text style={styles.listItem}>• Cookies and Usage Data</Text>
          </View>
          <Text style={styles.paragraph}>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
          </Text>

          <Text style={styles.subsectionTitle}>Usage Data</Text>
          <Text style={styles.paragraph}>
            We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<Text style={styles.bold}>"Usage Data"</Text>).
          </Text>
          <Text style={styles.paragraph}>
            This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </Text>
          <Text style={styles.paragraph}>
            When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
          </Text>

          <Text style={styles.subsectionTitle}>Location Data</Text>
          <Text style={styles.paragraph}>
            We may use and store information about your location if you give us permission to do so (<Text style={styles.bold}>"Location Data"</Text>). We use this data to provide features of our Service, to improve and customize our Service.
          </Text>
          <Text style={styles.paragraph}>
            You can enable or disable location services when you use our Service at any time by way of your device settings.
          </Text>

          <Text style={styles.subsectionTitle}>Tracking Cookies Data</Text>
          <Text style={styles.paragraph}>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
          </Text>
          <Text style={styles.paragraph}>
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
          </Text>
          <Text style={styles.paragraph}>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </Text>
          <Text style={styles.paragraph}>Examples of Cookies we use:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>
              • <Text style={styles.bold}>Session Cookies:</Text> We use Session Cookies to operate our Service.
            </Text>
            <Text style={styles.listItem}>
              • <Text style={styles.bold}>Preference Cookies:</Text> We use Preference Cookies to remember your preferences and various settings.
            </Text>
            <Text style={styles.listItem}>
              • <Text style={styles.bold}>Security Cookies:</Text> We use Security Cookies for security purposes.
            </Text>
            <Text style={styles.listItem}>
              • <Text style={styles.bold}>Advertising Cookies:</Text> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
            </Text>
          </View>

          <Text style={styles.subsectionTitle}>Other Data</Text>
          <Text style={styles.paragraph}>
            While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements,{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/non-disclosure-agreement/')}>
              NDA agreements
            </Text>, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>5. Use of Data</Text>
          <Text style={styles.paragraph}>Labor Link Pvt Ltd uses the collected data for various purposes:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• to provide and maintain our Service;</Text>
            <Text style={styles.listItem}>• to notify you about changes to our Service;</Text>
            <Text style={styles.listItem}>• to allow you to participate in interactive features of our Service when you choose to do so;</Text>
            <Text style={styles.listItem}>• to provide customer support;</Text>
            <Text style={styles.listItem}>• to gather analysis or valuable information so that we can improve our Service;</Text>
            <Text style={styles.listItem}>• to monitor the usage of our Service;</Text>
            <Text style={styles.listItem}>• to detect, prevent and address technical issues;</Text>
            <Text style={styles.listItem}>• to fulfil any other purpose for which you provide it;</Text>
            <Text style={styles.listItem}>• to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</Text>
            <Text style={styles.listItem}>• to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</Text>
            <Text style={styles.listItem}>• to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</Text>
            <Text style={styles.listItem}>• in any other way we may describe when you provide the information;</Text>
            <Text style={styles.listItem}>• for any other purpose with your consent.</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>6. Retention of Data</Text>
          <Text style={styles.paragraph}>
            We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </Text>
          <Text style={styles.paragraph}>
            We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>7. Transfer of Data</Text>
          <Text style={styles.paragraph}>
            Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
          </Text>
          <Text style={styles.paragraph}>
            If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
          </Text>
          <Text style={styles.paragraph}>
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          </Text>
          <Text style={styles.paragraph}>
            Labor Link Pvt Ltd will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>8. Disclosure of Data</Text>
          <Text style={styles.paragraph}>We may disclose personal information that we collect, or you provide:</Text>

          <Text style={styles.subsectionTitle}>Disclosure for Law Enforcement</Text>
          <Text style={styles.paragraph}>
            Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
          </Text>

          <Text style={styles.subsectionTitle}>Business Transaction</Text>
          <Text style={styles.paragraph}>
            If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
          </Text>

          <Text style={styles.subsectionTitle}>Other cases. We may disclose your information also:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• to our subsidiaries and affiliates;</Text>
            <Text style={styles.listItem}>• to contractors, service providers, and other third parties we use to support our business;</Text>
            <Text style={styles.listItem}>• to fulfill the purpose for which you provide it;</Text>
            <Text style={styles.listItem}>• for the purpose of including your company's logo on our website;</Text>
            <Text style={styles.listItem}>• for any other purpose disclosed by us when you provide the information;</Text>
            <Text style={styles.listItem}>• with your consent in any other cases;</Text>
            <Text style={styles.listItem}>• if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>9. Security of Data</Text>
          <Text style={styles.paragraph}>
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</Text>
          <Text style={styles.paragraph}>
            If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
          </Text>
          <Text style={styles.paragraph}>
            We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
          </Text>
          <Text style={styles.paragraph}>
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at{' '}
            <Text style={styles.link} onPress={() => handleEmailPress('labourlink2025@gmail.com')}>
              labourlink2025@gmail.com
            </Text>.
          </Text>
          <Text style={styles.paragraph}>In certain circumstances, you have the following data protection rights:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• the right to access, update or to delete the information we have on you;</Text>
            <Text style={styles.listItem}>• the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</Text>
            <Text style={styles.listItem}>• the right to object. You have the right to object to our processing of your Personal Data;</Text>
            <Text style={styles.listItem}>• the right of restriction. You have the right to request that we restrict the processing of your personal information;</Text>
            <Text style={styles.listItem}>• the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</Text>
            <Text style={styles.listItem}>• the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</Text>
          </View>
          <Text style={styles.paragraph}>
            Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
          </Text>
          <Text style={styles.paragraph}>
            You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</Text>
          <Text style={styles.paragraph}>
            CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.
          </Text>
          <Text style={styles.paragraph}>According to CalOPPA we agree to the following:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• users can visit our site anonymously;</Text>
            <Text style={styles.listItem}>• our Privacy Policy link includes the word "Privacy", and can easily be found on the home page of our website;</Text>
            <Text style={styles.listItem}>• users will be notified of any privacy policy changes on our Privacy Policy Page;</Text>
            <Text style={styles.listItem}>
              • users are able to change their personal information by emailing us at{' '}
              <Text style={styles.link} onPress={() => handleEmailPress('labourlink2025@gmail.com')}>
                labourlink2025@gmail.com
              </Text>.
            </Text>
          </View>
          <Text style={styles.paragraph}>Our Policy on "Do Not Track" Signals:</Text>
          <Text style={styles.paragraph}>
            We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
          </Text>
          <Text style={styles.paragraph}>
            You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</Text>
          <Text style={styles.paragraph}>
            If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
          </Text>

          <Text style={styles.subsectionTitle}>What personal information we have about you. If you make this request, we will return to you:</Text>
          <View style={styles.listContainer}>
            <Text style={styles.listItem}>• The categories of personal information we have collected about you.</Text>
            <Text style={styles.listItem}>• The categories of sources from which we collect your personal information.</Text>
            <Text style={styles.listItem}>• The business or commercial purpose for collecting or selling your personal information.</Text>
            <Text style={styles.listItem}>• The categories of third parties with whom we share personal information.</Text>
            <Text style={styles.listItem}>• The specific pieces of personal information we have collected about you.</Text>
            <Text style={styles.listItem}>• A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</Text>
            <Text style={styles.listItem}>• A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</Text>
          </View>
          <Text style={styles.paragraph}>
            Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
          </Text>

          <Text style={styles.subsectionTitle}>To delete your personal information.</Text>
          <Text style={styles.paragraph}>
            If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
          </Text>

          <Text style={styles.subsectionTitle}>To stop selling your personal information.</Text>
          <Text style={styles.paragraph}>
            We don't sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a "sale" under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
          </Text>
          <Text style={styles.paragraph}>
            If you submit a request to stop selling your personal information, we will stop making such transfers.
          </Text>
          <Text style={styles.paragraph}>
            Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
          </Text>
          <Text style={styles.paragraph}>
            To exercise your California data protection rights described above, please send your request(s) by email:{' '}
            <Text style={styles.link} onPress={() => handleEmailPress('labourlink2025@gmail.com')}>
              labourlink2025@gmail.com
            </Text>.
          </Text>
          <Text style={styles.paragraph}>
            Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>13. Service Providers</Text>
          <Text style={styles.paragraph}>
            We may employ third party companies and individuals to facilitate our Service (<Text style={styles.bold}>"Service Providers"</Text>), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
          </Text>
          <Text style={styles.paragraph}>
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>14. Analytics</Text>
          <Text style={styles.paragraph}>
            We may use third-party Service Providers to monitor and analyze the use of our Service.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>15. CI/CD tools</Text>
          <Text style={styles.paragraph}>
            We may use third-party Service Providers to automate the development process of our Service.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>16. Behavioral Remarketing</Text>
          <Text style={styles.paragraph}>
            We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>17. Links to Other Sites</Text>
          <Text style={styles.paragraph}>
            Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          </Text>
          <Text style={styles.paragraph}>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </Text>
          <Text style={styles.paragraph}>
            For example, the outlined{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/privacy/')}>
              privacy policy
            </Text>{' '}
            has been made using{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/')}>
              laborlink.co.in
            </Text>, a free tool that helps create high-quality legal documents. LaborLink's{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/privacy/')}>
              privacy policy generator
            </Text>{' '}
            is an easy-to-use tool for creating a{' '}
            <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/blog-privacy-policy/')}>
              privacy policy for blog
            </Text>, website, e-commerce store or mobile app.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>18. Children's Privacy</Text>
          <Text style={styles.paragraph}>
            Our Services are not intended for use by children under the age of 18 (<Text style={styles.bold}>"Child"</Text> or <Text style={styles.bold}>"Children"</Text>).
          </Text>
          <Text style={styles.paragraph}>
            We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>19. Changes to This Privacy Policy</Text>
          <Text style={styles.paragraph}>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
          </Text>
          <Text style={styles.paragraph}>
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.
          </Text>
          <Text style={styles.paragraph}>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </Text>
        </View> 
           <View style={styles.section}>
          <Text style={styles.sectionTitle}>20. Contact Us</Text>
          <Text style={styles.paragraph}>
            If you have any questions about this Privacy Policy, please contact us by email:{' '}
            <Text style={styles.link} onPress={() => handleEmailPress('labourlink2025@gmail.com')}>
              labourlink2025@gmail.com
            </Text>.
          </Text>
        </View> 
         
            <View style={styles.section}>
          <Text style={styles.sectionTitle}>21. Refund Policy </Text>
          <Text style={styles.paragraph}>
  For approved refunds, we will credit the refundable amount into the source account within 5-7 business days
        
          </Text>
        </View>

    
        <Text style={styles.footer}>
          This{' '}
          <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500/privacy/')}>
            Privacy Policy
          </Text>{' '}
          was created for{' '}
          <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500')}>
            http://localhost:8500
          </Text>{' '}
          by{' '}
          <Text style={styles.link} onPress={() => handleLinkPress('http://localhost:8500')}>
            laborlink.co.in
          </Text>{' '}
          on 2025-06-13.
        </Text>
      </View>
    </ScrollView>
  );
};
export default Privacy;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  content: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginVertical: 20,
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 20,
  },
  effectiveDate: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 20,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  subsectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
    marginTop: 16,
  },
  paragraph: {
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 24,
    marginBottom: 12,
  },
  bold: {
    fontWeight: '600',
    color: '#1f2937',
  },
  link: {
    color: '#2563eb',
    textDecorationLine: 'underline',
  },
  listContainer: {
    marginLeft: 8,
    marginBottom: 12,
  },
  listItem: {
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 24,
    marginBottom: 8,
  },
  footer: {
    fontSize: 12,
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 18,
    fontStyle: 'italic',
  },
});